speech:
  engine: "groq"
  source: "STEREO_MIX" # Options: MICROPHONE, STEREO_MIX
ai:
  provider: "groq"
spring:
  config:
    import: "optional:classpath:secrets.yml"
  ai:
    google:
      genai:
        api-key: ${google.api.key}
        chat:
          options:
            model: gemini-2.5-flash
  threads:
    virtual:
      enabled: true
  application:
    name: demo
